const GET_INITIAL_DATA = "GET_INITIAL_DATA";
const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
const GET_PRODUCTS = "GET_PRODUCTS";
const DELETE_SHOPPING_LIST = "DELETE_SHOPPING_LIST";

module.exports = {
  GET_INITIAL_DATA,
  GET_SHOPPING_LIST,
  GET_PRODUCTS,
  DELETE_SHOPPING_LIST,
};
