module.exports = {
  GET_INITIAL_DATA: "GET_INITIAL_DATA",
  GET_SHOPPING_LIST: "GET_SHOPPING_LIST",
  GET_PRODUCTS: "GET_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  DELETE_SHOPPING_LIST: "DELETE_SHOPPING_LIST",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  GET_NEW_PRODUCT: "GET_NEW_PRODUCT",
};
